#!/usr/bin/env bash

set -x

profile=$1

pkill -f "dunst\s|dunst$"
pkill -f notify-osd

set -e

if [ "$profile" = "" ]; then
    dunst -config "~/.config/dunst/dunstrc" &
    notify-send -u critical system "switching to default config"
else
    dunst -config "~/.config/dunst/dunstrc_$profile" &
    notify-send -u critical system "switching to profile $profile"
fi
