#!/usr/bin/env bash

set -xu

profile=$1

pkill -f "dunst\s|dunst$"
pkill -f notify-osd

set -e
dunst -config "~/.config/dunst/dunstrc_$profile" &
notify-send -u critical system "switching to profile $profile"
