#!/usr/bin/env bash

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

kitty weechat &

swayidle -w timeout 600 hyprlock & # lock screen after 10 min of idle

sleep 2
# without this I have no sound
/home/stefan/.bin/fix-sound

sleep infinity
