#!/usr/bin/env bash

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

if command -v wob &>/dev/null; then
    mkfifo /tmp/wobpipe
    tail -f /tmp/wobpipe | wob &
fi

lowbattery &

slack &

swaybg -m fill -i ~/.wallpapers/highway_by_axiomdesign-d9em9fs.jpg &

timeout=600
[[ "$(hostname)" == "bjorn" ]] && timeout=7200
swayidle -w timeout "$timeout" hyprlock &

sleep infinity
